const root=document.getElementById('app');
let discovery,state=null,view='compare',busy=false,ready=0,error='',pending=null;
let drafts={},pairNotes={},sessions=[],rankingRows=[];
const params=new URLSearchParams(location.search),rehearsal=params.get('rehearsal')==='1';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const iconPaths={brand:'M3 4h5v12H3zM12 4h5v12h-5z',menu:'M4 5h12M4 10h12M4 15h12',layout:'M3 4h14v12H3zM3 8h14M10 8v8',grid:'M3 3h5v5H3zM12 3h5v5h-5zM3 12h5v5H3zM12 12h5v5h-5z',rank:'M4 16V9h4v7m0 0V4h4v12m0 0v-5h4v5M3 16h14',download:'M10 3v9m-4-4 4 4 4-4M3 12v5h14v-5',folder:'M3 5h5l2 2h7v10H3z',open:'M11 3h6v6M17 3l-8 8M8 3H3v14h14v-5',save:'M3 3h12l2 2v12H3zM6 3v5h8V3M6 17v-6h8v6',undo:'M7 4 3 8l4 4M3 8h8a5 5 0 0 1 0 10',refresh:'M16 7a7 7 0 1 0 1 6M16 3v5h-5',plus:'M10 4v12M4 10h12',back:'m9 4-6 6 6 6M3 10h14',skip:'M3 10h11m-4-4 4 4-4 4m7-10v12',check:'m4 10 4 4 8-8',cross:'m5 5 10 10M15 5 5 15'};
function icon(name){return `<svg class="icon" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><path d="${iconPaths[name]}"/></svg>`;}
const candidate=id=>state.candidates.find(c=>c.id===id);
function accept(result){state=result.state;rankingRows=result.standings;}
const storageKey=()=>state?'tot-tournament-draft:'+state.id:null;
function persist(){try{if(state)localStorage.setItem(storageKey(),JSON.stringify({drafts,pairNotes,pending}));}catch{error='Browser draft storage unavailable. Save notes before closing.';showError();}}
function recover(){try{const saved=JSON.parse(localStorage.getItem(storageKey())||'{}');drafts=saved.drafts||{};pairNotes=saved.pairNotes||{};pending=saved.pending||null;}catch{drafts={};pairNotes={};pending=null;}reconcile();}
function reconcile(){for(const [id,text] of Object.entries(drafts))if(state.notes[id]===text)delete drafts[id];if(pending&&state.receipts.some(r=>r.id===pending.requestId)){if((pending.action.type==='vote'||pending.action.type==='feedback'))delete pairNotes[pending.action.pairId];pending=null;}persist();}
async function request(path,body){const response=await fetch(path,{method:body?'POST':'GET',headers:body?{'content-type':'application/json','x-tot-client':'ui','x-tot-nonce':discovery.nonce}:{},body:body?JSON.stringify(body):undefined});const result=await response.json();if(!response.ok||result.ok===false)throw new Error(result.error?.message||`HTTP ${response.status}`);return result;}
function status(){const node=document.getElementById('status');if(node)node.textContent=busy?'Saving…':pending?'Choice needs recovery':Object.keys(drafts).length?'Notes saved in this browser':state?`Saved · ${state.comparisons.length} choices`:'Exploration drafts';}
function controls(){for(const button of document.querySelectorAll('button'))button.disabled=busy;for(const button of document.querySelectorAll('[data-mutate]'))button.disabled=busy||!!pending;for(const button of document.querySelectorAll('.vote'))button.disabled=busy||!!pending||ready<2;const undo=document.getElementById('undo');if(undo)undo.disabled=busy||!!pending||state?.comparisons.at(-1)?.pass!==state?.pass;for(const textarea of document.querySelectorAll('textarea[data-note],#pair-note'))textarea.readOnly=busy;status();}
function showError(){const box=document.getElementById('error');if(!box)return;box.hidden=!error&&!pending;box.querySelector('p').textContent=error||(pending?'A request has not been acknowledged. Retry it without changing the choice.':'');box.querySelector('#retry').hidden=!pending;box.querySelector('#recover').hidden=!pending;}
async function sendEnvelope(envelope,redraw=true){if(busy)return false;busy=true;pending=envelope;persist();controls();error='';showError();try{const result=await request(`/api/v2/tournaments/${state.id}/actions`,envelope);accept(result);if((envelope.action.type==='vote'||envelope.action.type==='feedback'))delete pairNotes[envelope.action.pairId];pending=null;reconcile();busy=false;if(redraw){if(state.order.length)view='results';render();}else{controls();showError();}return true;}catch(e){busy=false;error=e.message;persist();controls();showError();return false;}}
async function mutate(action,redraw=true){if(busy||pending)return false;return sendEnvelope({requestId:crypto.randomUUID(),expectedRevision:state.revision,action},redraw);}
async function saveNotes(){if(busy||pending)return false;for(const [id,text] of Object.entries({...drafts}))if(!await mutate({type:'note',candidateId:id,text},false))return false;return true;}
async function choose(side){if(!state?.pair||busy||pending||ready<2)return;const pair=state.pair;await mutate({type:'vote',pairId:pair.id,winner:pair[side],note:pairNotes[pair.id]||'',notes:{...drafts}});}
async function feedback(outcome){if(!state?.pair||busy||pending||ready<2)return;const pair=state.pair;await mutate({type:'feedback',pairId:pair.id,outcome,note:pairNotes[pair.id]||'',notes:{...drafts}});}
async function load(id){busy=true;try{const result=await request('/api/v2/tournaments/'+id);accept(result);view=state.order.length?'results':'compare';error='';recover();params.set('session',id);history.replaceState(null,'','?'+params);busy=false;render();}catch(e){busy=false;error=e.message;render();}}
async function create(options){if(busy)return;busy=true;controls();try{const body={requestId:crypto.randomUUID(),mode:rehearsal?'rehearsal':'human'};if(options){body.title=options.title;body.options=options.options;}const result=await request('/api/v2/tournaments',body);accept(result);drafts={};pairNotes={};pending=null;error='';view='compare';params.set('session',state.id);history.replaceState(null,'','?'+params);persist();busy=false;render();}catch(e){busy=false;error=e.message;render();}}
async function download(format){if(!await saveNotes())return;const response=await fetch(`/api/v2/tournaments/${state.id}/export?format=${format}`);if(!response.ok){error=(await response.json()).error.message;showError();return;}const blob=await response.blob(),href=URL.createObjectURL(blob),link=document.createElement('a');link.href=href;link.download=format==='html'?`winner-${state.winnerId}.html`:`this-or-that-${state.id}.${format}`;link.click();setTimeout(()=>URL.revokeObjectURL(href),1000);}
function header(){const seen=state?new Set(state.comparisons.flatMap(v=>[v.left,v.right])).size:0;return `<header class="topbar"><span class="brand">${icon('brand')}<span>This or that</span></span><div class="title"><h1>${esc(state?.title||discovery.catalog.title)}</h1><small>${state?`Pass ${state.pass} · Stage ${state.stage}/${Math.ceil(Math.log2(state.candidates.length))} · ${seen}/${state.candidates.length} seen · ${state.comparisons.length} choices`:'20 new directions + 2 incumbents'}</small></div>${(state?.mode==='rehearsal'||rehearsal)?'<span class="rehearsal">Rehearsal · not human evidence</span>':''}<span id="status" class="status"></span><div class="appearance"><label for="appearance-mode">Appearance</label><select id="appearance-mode" aria-describedby="appearance-status"><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select><span id="appearance-status" class="status" role="status"></span></div><details id="tournament-menu"><summary id="navigation-toggle" role="button" aria-controls="tournament-navigation" aria-expanded="false">More${icon('menu')}</summary><nav id="tournament-navigation" class="actions" aria-label="Tournament"><a id="chrome-mockups" href="/mockups">${icon('layout')}Chrome mockups</a><button id="browse">${icon('grid')}All candidates</button>${state?`<button id="rankings">${icon('rank')}Rankings</button><button id="export-json" data-mutate>${icon('download')}Export JSON</button><button id="home">${icon('folder')}Sessions</button>`:''}</nav></details></header><section id="error" class="error" hidden><p></p><button id="retry">${icon('refresh')}Retry saved request</button><button id="recover">${icon('folder')}Inspect saved state</button></section>`;}
function sessionManager(){return `<main class="home"><div class="gallery-heading"><h1>Sessions</h1><div class="actions"><button class="primary" id="new-comparison" data-mutate>${icon('plus')}New comparison</button>${state?`<button id="back">${icon('back')}Back to comparison</button>`:''}</div></div><p><a href="/mockups">Chrome mockups</a> · Preview eighteen comparison designs without recording rankings or changing your candidates.</p><section><h2>Resume a comparison</h2><div class="session-list">${sessions.length?sessions.map(s=>`<button data-session="${esc(s.id)}"><span>${esc(s.title)} <small>· ${esc(s.mode)}</small></span><small>${s.comparisons} choices · ${s.complete?'ranked':'in progress'}</small></button>`).join(''):'<p class="muted">Your first comparison starts fresh.</p>'}</div></section><details><summary>Use another collection</summary><p class="method">Place HTML demos in tournament/candidates, then paste a manifest: {"title":"…","options":[{"id":"one","name":"…","src":"/candidates/one.html"}, …]}. Any visual, API explorer or interactive demo can be a candidate. Two to 200 candidates.</p><textarea id="manifest" aria-label="Candidate collection JSON" placeholder='{"title":"My variations","options":[]}'></textarea><button id="import" data-mutate>${icon('plus')}Start this collection</button></details></main>`;}
function card(side){const c=candidate(state.pair[side]),left=side==='left';return `<section class="candidate" data-side="${side}" aria-label="${side} candidate"><header class="candidate-head"><div class="candidate-heading-row"><div class="folio-heading"><span class="page-marker" aria-hidden="true">${left?'L':'R'}</span><h2>${esc(c.name)}</h2></div><div class="decision"><button class="vote" id="choose-${side}" aria-label="Choose ${esc(c.name)}" aria-keyshortcuts="${left?'ArrowLeft':'ArrowRight'}" data-mutate><span class="check" aria-hidden="true">${icon('check')}</span><span>Choose</span><kbd>${left?'←':'→'}</kbd></button></div></div><div class="folio-meta"><span>${left?'Left':'Right'} candidate · ${esc(c.id)}</span><a href="${esc(c.src)}" target="_blank" rel="noopener" aria-label="Open ${esc(c.name)} larger in a new tab">Open larger${icon('open')}</a></div></header><div class="frame-wrap"><iframe id="frame-${side}" title="${esc(c.name)}" src="${esc(c.src)}" sandbox="allow-scripts allow-same-origin"></iframe><div class="frame-status">Opening candidate…</div></div><div class="candidate-note"><div class="annotation-label"><label for="note-${c.id}">Notes on ${esc(c.name)}</label><span class="optional">Optional</span></div><textarea id="note-${c.id}" data-note="${c.id}" rows="2" placeholder="What works? What gets in the way?">${esc(drafts[c.id]??state.notes[c.id])}</textarea></div></section>`;}
function compare(){return `<main class="workspace" tabindex="-1"><div class="pair">${card('left')}${card('right')}</div><div class="feedback-row" role="group" aria-label="Comparison response tools"><button class="vote feedback" id="skip" aria-keyshortcuts="s" data-mutate title="Move on without changing either score">${icon('skip')}<span>Skip</span> <kbd>S</kbd> <small>no score change</small></button><button class="vote feedback" id="like-both" aria-keyshortcuts="l" data-mutate title="Add 16 preference points to both candidates">${icon('check')}<span>Like both</span> <kbd>L</kbd> <small>+16 each</small></button><button class="vote feedback" id="hate-both" aria-keyshortcuts="h" data-mutate title="Subtract 16 preference points from both candidates">${icon('cross')}<span>Hate both</span> <kbd>H</kbd> <small>−16 each</small></button><div class="response-tools"><button id="save-notes" data-mutate>${icon('save')}Save notes</button><button id="undo" data-mutate ${state.comparisons.at(-1)?.pass===state.pass?'':'disabled'}>${icon('undo')}Undo response</button></div></div><div class="bottom"><label for="pair-note">Feedback</label><textarea id="pair-note" aria-keyshortcuts="Tab" placeholder="Optional feedback · Tab to focus or leave">${esc(pairNotes[state.pair.id]||'')}</textarea><small id="key-hint">S skip · H hate · L like · Tab feedback · Esc leaves demo</small></div></main>`;}
function gallery(){const options=state?.candidates||discovery.catalog.options;return `<main class="gallery" tabindex="-1"><div class="gallery-heading"><div><h1>${options.length} different approaches</h1><p class="method">Same eight tickets. Different interaction ideas. Try a demo here; choose between pairs to rank them. Esc returns to the gallery controls.</p></div><button id="back">${icon('back')}Back</button></div><div class="gallery-grid">${options.map(c=>`<article class="gallery-card"><div class="preview"><iframe id="gallery-frame-${esc(c.id)}" title="${esc(c.name)} preview" src="${esc(c.src)}" loading="lazy" sandbox="allow-scripts allow-same-origin"></iframe></div><div class="copy"><h3><span class="number">${esc(c.id)}</span> ${esc(c.name)}</h3><p>${esc(c.description)}</p><a href="${esc(c.src)}" target="_blank" rel="noopener">Open larger${icon('open')}</a></div></article>`).join('')}</div></main>`;}
function rows(){return rankingRows.map(row=>{const c=row.candidate,r=state.ratings[c.id];return `<tr><td>${row.rank??'—'}</td><td><strong>${esc(c.name)}</strong><br><small>${esc(c.id)}</small> · <a href="${esc(c.src)}" target="_blank" rel="noopener">Open</a>${!r.assessed?'<br><small>Unassessed</small>':''}</td><td>${r.assessed?r.score.toFixed(1):'—'}<br><small>${r.wins}W / ${r.losses}L</small><br><small>${r.likes} likes · ${r.hates} hates · ${r.skips} skips</small></td><td><textarea aria-label="Notes on ${esc(c.name)}" data-note="${c.id}">${esc(drafts[c.id]??state.notes[c.id])}</textarea></td></tr>`;}).join('');}
function results(){const complete=!!state.order.length,winner=state.winnerId?candidate(state.winnerId):null;return `<main class="results"><div class="results-heading"><h1>${complete?'Your ranked directions':'Ranking in progress'}</h1><div class="actions"><button id="back">${icon('back')}${complete?'View all candidates':'Keep comparing'}</button><button id="save-notes" data-mutate>${icon('save')}Save notes</button></div></div>${winner?`<section class="winner"><div><p>Highest-scoring assessed candidate · pass ${state.pass}</p><h2>${esc(winner.name)}</h2><p>${esc(state.notes[winner.id]||'No candidate note recorded yet.')}</p></div><button id="winner-html" data-mutate>${icon('download')}Export winner HTML</button></section>`:complete?'<section class="no-winner"><h2>No unique winner yet</h2><p>Equal scores share a rank. Candidates you only skipped remain unassessed. Another pass can separate the contenders.</p></section>':'<p class="method">Finish this pass for final standings. Scores are provisional while comparisons remain.</p>'}<div class="actions"><button id="json-download" data-mutate>${icon('download')}Export agent package · JSON</button><button id="markdown-download" data-mutate>${icon('download')}Export notes · Markdown</button>${complete?`<button id="refine" data-mutate>${icon('refresh')}Rank another pass</button><button id="undo" data-mutate>${icon('undo')}Undo last response</button>`:''}</div><p class="method">Ranking score = Elo from left/right choices + 16 × (likes − hates). Like both boosts both equally; Hate both lowers both equally, without recording a winner or loser. Skip changes no score. Equal scores share a rank; unassessed candidates cannot win. The merge-style schedule organizes the matchups, not the final ordering. Notes and every response travel with the export.</p><div class="table-wrap"><table class="ranking-table"><thead><tr><th>Rank</th><th>Candidate</th><th>Score and feedback</th><th>Your notes</th></tr></thead><tbody>${rows()}</tbody></table></div></main>`;}
const comparisonHover=matchMedia('(hover: hover)');
function inspectComparisonInteraction(){const pair=view==='compare'?document.querySelector('.pair'):null,left=pair?.querySelector('.candidate[data-side="left"]'),right=pair?.querySelector('.candidate[data-side="right"]'),available=!!left&&!!right,hoveredSide=available&&comparisonHover.matches?(left.matches(':hover')?'left':right.matches(':hover')?'right':null):null,focusedSide=available?(left.matches(':focus-within')?'left':right.matches(':focus-within')?'right':null):null;return {available,hoveredSide,focusedSide,emphasizedSide:hoveredSide??focusedSide};}
let navigationRevision=0,navigationOpen=false,navigationAvailable=false;
function inspectNavigation(){const menu=document.getElementById('tournament-menu'),toggle=document.getElementById('navigation-toggle'),nav=document.getElementById('tournament-navigation'),available=menu instanceof HTMLDetailsElement&&!!toggle&&!!nav,expanded=available&&menu.open;if(expanded!==navigationOpen||available!==navigationAvailable){navigationRevision++;navigationOpen=expanded;navigationAvailable=available;}toggle?.setAttribute('aria-expanded',String(expanded));return {id:'navigation-toggle',role:'button',expanded,revision:navigationRevision,available,controls:available?[...nav.querySelectorAll('a[id],button[id]')].map(control=>control.id):[]};}
function setNavigation(request){const navigation=inspectNavigation(),failure=(code,message)=>({ok:false,error:{code,message},navigation});if(!request||typeof request!=='object'||Array.isArray(request)||Object.keys(request).some(key=>key!=='expectedRevision'&&key!=='open')||!Number.isSafeInteger(request.expectedRevision)||request.expectedRevision<0||typeof request.open!=='boolean')return failure('INVALID_REQUEST','Provide expectedRevision and open: true or false.');if(request.expectedRevision!==navigation.revision)return failure('STALE_REVISION','Navigation changed. Inspect the current revision before trying again.');if(!navigation.available)return failure('UNAVAILABLE','Tournament navigation is not mounted.');document.getElementById('tournament-menu').open=request.open;return {ok:true,navigation:inspectNavigation()};}
function closeNavigation(restoreFocus=false){const navigation=inspectNavigation();if(!navigation.expanded)return;setNavigation({expectedRevision:navigation.revision,open:false});if(restoreFocus)document.getElementById('navigation-toggle')?.focus({preventScroll:true});}
function focusComparison(){const control=document.getElementById(view==='compare'?'choose-left':view==='gallery'?'back':'');if(!control)return false;const target=control.disabled?control.closest('main'):control;target?.focus({preventScroll:true});return !!target&&document.activeElement===target;}
function on(id,handler){document.getElementById(id)?.addEventListener('click',handler);}
function render(){inspectNavigation();root.innerHTML=header()+(view==='gallery'?gallery():!state||view==='sessions'?sessionManager():view==='results'?results():compare());ready=0;
  document.getElementById('tournament-menu').addEventListener('toggle',inspectNavigation);inspectNavigation();
  on('new-comparison',()=>create());on('import',()=>{try{create(JSON.parse(document.getElementById('manifest').value));}catch(e){error=e.message;showError();}});
  for(const b of document.querySelectorAll('[data-session]'))b.onclick=()=>load(b.dataset.session);
  on('browse',()=>{view='gallery';render();});on('rankings',()=>{view='results';render();});on('back',()=>{view=!state?'sessions':view==='gallery'?(state.order.length?'results':'compare'):(state.order.length?'gallery':'compare');render();});
  on('home',async()=>{if(busy)return;try{sessions=(await request('/api/v2/tournaments')).sessions;view='sessions';render();}catch(e){error=e.message;showError();}});
  on('choose-left',()=>choose('left'));on('choose-right',()=>choose('right'));on('save-notes',()=>saveNotes());for(const outcome of ['skip','like-both','hate-both'])on(outcome,()=>feedback(outcome));
  on('undo',async()=>{if(await saveNotes()){const note=state.comparisons.at(-1)?.note;view='compare';if(await mutate({type:'undo'})&&state.pair&&note){pairNotes[state.pair.id]=note;persist();document.getElementById('pair-note').value=note;}}});
  on('refine',async()=>{if(await saveNotes()){view='compare';await mutate({type:'refine'});}});
  for(const id of ['export-json','json-download'])on(id,()=>download('json'));on('markdown-download',()=>download('md'));on('winner-html',()=>download('html'));
  on('retry',async()=>{discovery=await request('/api/v2/discover');if(pending)await sendEnvelope(pending);});
  on('recover',async()=>{const result=await request('/api/v2/tournaments/'+state.id);accept(result);reconcile();if(pending&&confirm('The server has no receipt for this request. Discard only the pending action and keep your notes?')){pending=null;persist();}error='';view=state.order.length?'results':'compare';render();});
  for(const input of document.querySelectorAll('[data-note]'))input.addEventListener('input',()=>{drafts[input.dataset.note]=input.value;persist();status();});
  document.getElementById('pair-note')?.addEventListener('input',event=>{pairNotes[state.pair.id]=event.target.value;persist();});
  for(const frame of document.querySelectorAll('.pair iframe'))frame.addEventListener('load',()=>{ready++;frame.nextElementSibling.hidden=true;controls();});
  controls();if(state&&!state.comparisons.some(v=>v.pass===state.pass))document.getElementById('undo')?.setAttribute('disabled','');showError();
  document.dispatchEvent(new Event('tournament:render'));
}
function isTextField(target){return target instanceof Element&&(target.isContentEditable||!!target.closest('textarea,input,select,[role="textbox"]'));}
function toggleFeedbackFocus(){const field=document.getElementById('pair-note');if(view!=='compare'||!field)return false;if(document.activeElement===field)field.blur();else field.focus();return document.activeElement===field;}
document.addEventListener('click',event=>{const menu=document.getElementById('tournament-menu');if(event.target instanceof Node&&!menu?.contains(event.target))closeNavigation();});
window.addEventListener('blur',()=>{setTimeout(()=>{if(document.activeElement instanceof HTMLIFrameElement)closeNavigation();},0);});
document.addEventListener('keydown',event=>{
  if(event.defaultPrevented||event.repeat||event.isComposing||event.altKey||event.ctrlKey||event.metaKey)return;
  if(event.key==='Escape'&&inspectNavigation().expanded){event.preventDefault();closeNavigation(true);return;}
  if(event.target instanceof Element&&event.target.closest('#tournament-menu'))return;
  if(view!=='compare'||!state?.pair)return;
  if(event.target instanceof Element&&event.target.closest('select,.appearance'))return;
  if(event.key==='Tab'&&!event.shiftKey){event.preventDefault();toggleFeedbackFocus();return;}
  if(isTextField(event.target))return;
  if(event.key==='ArrowLeft'||event.key==='ArrowRight'){event.preventDefault();void choose(event.key==='ArrowLeft'?'left':'right');return;}
  const key=event.key.toLowerCase(),outcome=key==='s'?'skip':key==='h'?'hate-both':key==='l'?'like-both':null;
  if(outcome){event.preventDefault();void feedback(outcome);}
});
window.addEventListener('message',event=>{if(event.origin===location.origin&&event.data?.type==='tot:exit-interaction'&&[...document.querySelectorAll('.pair iframe,.gallery iframe')].some(frame=>frame.contentWindow===event.source))focusComparison();});
Object.assign(window.tournament,{inspect:()=>{const focused=document.activeElement,focusedFrame=focused instanceof HTMLIFrameElement?focused.id:null,textEditing=isTextField(focused),navigation=inspectNavigation();return {state,view,busy,dirtyNotes:{...drafts},comparisonNotes:{...pairNotes},pending,focusedControl:focused?.id||null,focusedFrame,textEditing,shortcutsAvailable:document.hasFocus()&&view==='compare'&&!!state?.pair&&!busy&&!pending&&ready>=2&&!focusedFrame&&!textEditing&&!focused?.closest('#tournament-menu'),comparisonInteraction:inspectComparisonInteraction(),navigation,appearance:window.tournament.appearance.inspect().state};},choose,feedback,focusComparison,toggleFeedbackFocus,saveNotes,setNavigation});
try{discovery=await request('/api/v2/discover');const id=params.get('session');if(id)await load(id);else await create();}catch(e){root.innerHTML=`<main class="home"><h1>Could not open the tournament</h1><p>${esc(e.message)}</p><p>Keep saved data intact. Restart the lesson server and reload.</p></main>`;}
